### ISSUE TITLE
slow on sat queries

### ISSUE THREAD

**Issue by dzufferey** [dreal/dreal3#147]
This is not really a bug, but performance are still important...

I have some sat queries and I'm interested in finding a solution, or intervals which are close enough to a solution. The queries are a mix of polynomial and trigonometric functions.

Below is a small example and my goal is to understand why dReal is slow with that kind of example and what could be done. I have much larger queries that are waiting.

I'm trying to understand how to the precision impacts the running time of dReal for sat queries (expecting the running time to be exponential in 1/δ).
In practice, the running time looks more like a few plateaux and _very_ sharp transitions between them.

For instance, on the example, the running time looks like:
* if δ ≥ 6.3 then solving takes less than 0.02s.
* if δ < 6.3 ∧ δ ≥ 2.246 then solving takes about 10s.
* if δ < 2.245 then solving takes 29 to 33s.

I would be interested to understand and if there are parameters/options, other than the precision, that could be used to make dReal faster on those queries.

Thanks,
Damien

-------------
```
(set-logic QF_NRA)
; variables
(declare-fun ua () Real) (declare-fun ui () Real)
(declare-fun uj () Real) (declare-fun uk () Real)
(declare-fun x () Real) (declare-fun y () Real) (declare-fun z () Real)
(declare-fun ba () Real) (declare-fun bk () Real)
(declare-fun alpha () Real) (declare-fun gamma () Real)
; bounds
(assert ( >= ua -1 ) ) (assert ( <= ua 1 ) )
(assert ( >= ui -1 ) ) (assert ( <= ui 1 ) )
(assert ( >= uj -1 ) ) (assert ( <= uj 1 ) )
(assert ( >= uk -1 ) ) (assert ( <= uk 1 ) )
(assert ( >= x -200 ) ) (assert ( <= x 200 ) )
(assert ( >= y -200 ) ) (assert ( <= y 200 ) )
(assert ( >= z -200 ) ) (assert ( <= z 200 ) )
(assert ( >= ba -1 ) ) (assert ( <= ba 1 ) )
(assert ( >= bk -1 ) ) (assert ( <= bk 1 ) )
(assert ( >= alpha -3.15 ) ) (assert ( <= alpha 3.15 ) )
(assert ( >= gamma -3.15 ) ) (assert ( <= gamma 3.15 ) )
; constraints
(assert ( = ( + ( ^ uk 2 ) ( ^ uj 2 ) ( ^ ui 2 ) ( ^ ua 2 ) ) 1 ) )
(assert ( = ( + ( ^ bk 2 ) ( ^ ba 2 ) ) 1 ) )
(assert ( = ( cos ( / gamma 2 ) ) ba ) )
(assert ( = ( sin ( / gamma 2 ) ) bk ) )
(assert ( = ( + ( * ( cos ( / alpha 2 ) ) ba ) ) ua ) )
(assert ( = ( + ( - ( * ( sin ( / alpha 2 ) ) bk ) ) ) ui ) )
(assert ( = ( + ( * ( sin ( / alpha 2 ) ) ba ) ) uj ) )
(assert ( = ( + ( * ( cos ( / alpha 2 ) ) bk ) ) uk ) )
(assert ( = ( + ( - ( * 148 ( ^ uk 2 ) ) ) ( - ( * 148 ( ^ uj 2 ) ) ) ( * 148 ( ^ ui 2 ) ) ( * 148 ( ^ ua 2 ) ) ) x ) )
(assert ( = ( + ( * 296 ua uk ) ( * 296 ui uj ) ) y ) )
(assert ( = ( + ( * 296 ui uk ) ( - ( * 296 ua uj ) ) ) z ) )
(check-sat)
(exit)
```

**Comment by scungao** [comment]
In this particular case, it seems if you allow delta to be >6.3 then
it covers the whole domain of alpha

(assert ( >= alpha -3.15 ) ) (assert ( <= alpha 3.15 ) )

which means the solver can return arbitrary values?

The difficulty with the instance is probably that the range of the
trigonometric functions are sort of linearly related (on top of their
square terms). It's hard to propagate values on the linear terms
(because of the constraints are "loose") and at the same time, the sin
and cos functions sort of block the propagation to the gamma and alpha
variables.

One possibility is to shrink the range on x and y -- the constraints
on them have constants that can be factored out. That'll help a bit
because they may shrink the range of the sin and cos terms which makes
that part of propagation easier.

In fact, I've just tried with dividing the coefficients and the range
of x,y,z by 1000 and it can be solved quickly with delta=0.0001.
That's kind of too good to be true, but you could probably try some
scaling like that and see if the solutions make sense. :)

**Comment by dzufferey** [comment]
Thanks,

I thought the δ was applied to the constraints (equalities and inequalities), but from your reply it seems that δ defines the sizes of the intervals of each variables, then the running times make more sense.

I'll try to scale the ranges and see how it goes. Actually what you did is pretty much what I did anyway, i.e., x,y,z does not need as much accuracy as ui,uj,uk,ua, so their domain can be shrunk (and the constraints scaled).

**Comment by scungao** [comment]
It is applied to the constraints indeed -- my explanation is probably not
right, now that I see those constraints on alpha and gamma are simple
bounds and should have been preprocessed already.

**Comment by soonhokong** [comment]
Using `--stat` option provides some statistics. Here is an example:

```
$ time ./dreal --precision 2.5 dz.smt2 --stat
delta-sat with delta = 2.50000000000000000
Number of Complete   Check = 1
Number of Incomplete Check = 1
Number of Assert           = 33
Number of Push             = 33
Number of Pop              = 0
Number of Branch           = 9950
Number of Prune            = 19883
Running time               = 23.117793 s
```

The example consists of a list of constraint (without any disjunction). So, most of the time is spent at ICP layer as the large numbers for branch and prune indicate. I've implemented a better worklist fixpoint algorithm for ICP (`--worklist-fp`) but it didn't help for this case. I plan to revisit this layer soon.
