### ISSUE TITLE
probably time to make dreal3 the default version

### ISSUE THREAD

**Issue by scungao** [dreal/dreal3#64]
Is it ready? 

update the dreal main repo with dreal3, and move the old version to a new repo dreal2

**Comment by soonhokong** [comment]
@scungao, @danbryce, and @pzuliani: let me summarize my thoughts into a note here instead of replying to the email. I think this place is better for the record.

Dependencies
--------------------

In terms of dependencies, we have two changes:

 - **Realpaver -> IBEX**: In dReal3, we dropped the [Realpaver][rp] dependency, and started using [IBEX][ibex]. This change has consequences because we have used Realpaver not as a pruning operator but as a main ICP algorithm. To introduce new functionalities such as different deltas, proof generation, etc, we had to modify the internals of Realpaver. In dReal3, we use IBEX only as a set of pruning operators while we take control of the ICP loop (see [nra_solver.cpp](https://github.com/dreal/dreal3/blob/master/src/dsolvers/nra_solver.cpp#L412-L414)). Essentially, all the things that we added to Realpaver's ICP part should be migrated to the `nra_solver` level.

[rp]: http://pagesperso.lina.univ-nantes.fr/~granvilliers-l/realpaver/
[ibex]: http://www.ibex-lib.org/

 - **Json11 -> Json**: We also have used [Dropbox's json11 library][json11] in dReal2. Honestly, I put it there but not really used it yet. I found that @danbryce actually used it in heuristics part to generate some extra Json output (I only skimmed through the codebase though). In dReal3, I used a different library - [json][json] when I reimplement the visualization part in [contractor_capd4.cpp](https://github.com/dreal/dreal3/blob/master/src/contractor/contractor_capd4.cpp#L572-L590). This change is mainly because of the license issue (json11 - Dropbox's own license, json - MIT license). I believe that both of json11 and json are simple libraries and the porting does not require a lot efforts.

[json11]: https://github.com/dropbox/json11
[json]: https://github.com/nlohmann/json


BMC (OCaml Code)
---------------------------

Obviously, this OCaml part is orthogonal to dReal2/3 which is written C++. Any changes made in dReal2 should be ported to dReal3 without a problem. I will do this soon.


dReach (Shellscript code)
-----------------------------------

Same thing. Must be easy to do. I'll finish this part soon.


dReal2 => dReal3 (C++)
---------------------------------

Let me enumerate the options that we do have in dReal2, but do not have yet in dReal3:

 - `--delta`
 - `--delta_heuristics`, `--bmc_heuristics`, `--plan_heuristics`
 - `--short_sat`
 - `--ode_sim_heuristic`, `--time_split_heuristic`
 - `--output_num_nodes`

I know @danbryce and SIFT people are using those options. @pzuliani, do your group also use one of the options above? Or is there anything that I missed in the list?

TODOs (from my side)
------------------------------

Other than the lack of supports to those options above, we're missing the following functionalities in dReal3 (which are available in dReal2): 

 1. Check simple mode invariants. See #42.
 2. We need to add simple ODE pruning to dReal3.
 3. Support `pintegral` and `connect` which are used by @kquine's work. There is an open issue for that https://github.com/dreal/dreal3/issues/28.

I wanted to make a public release of dReal3 and make it a default one instead of dReal2 after finishing item 1 and item 2. I think it can be done by next week. Of course, I'm happy to know your opinions on the matter. @pzuliani and @shmarovfedor, do you think your tools can work with dReal3? If not, what's missed here?

**Comment by scungao** [comment]
Wow...

**Comment by pzuliani** [comment]
that's great @soonhokong ! We use dReal/dReach pretty much in a plug-n-play fashion. For dReal I think we only need --precision; for dReach we use -z and the bounds flags. Anything else @shmarovfedor ?

**Comment by shmarovfedor** [comment]
No. Those are the only options we are currently using.

**Comment by pzuliani** [comment]
@soonhokong : why don't just run all the heuristics in parallel, and stop when the fastest finishes? This can be easily done with OpenMP ...

**Comment by soonhokong** [comment]
1. @pzuliani and @shmarovfedor, great! Now, my main concern is performance. Could you send me SMT2 files that you generated in your projects? I want to make sure that using dReal3 does not slow down your tools.

2. @pzuliani, we're thinking about using multi-threads inside of a solver. Then it's not really free to use multiple-threads outside of the solver (or using OpenMP). Definitely, parallelization is one thing I really want to do. I'll share a note later.

**Comment by danbryce** [comment]
@soonho Is it possible to use the new json dependency in dreal2?  I couldn’t find any references in the CMakeLists.txt.  I only saw a reference at https://github.com/dreal/dreal3/blob/master/src/contractor/contractor_capd4.cpp#L50-L50

Is it in IBEX?

**Comment by soonhokong** [comment]
> Is it possible to use the new json dependency in dreal2?

Yes. You can copy https://github.com/dreal/dreal3/blob/master/src/CMakeLists.txt#L306-L318 and paste them into CMakeLists.txt file in dReal2.

**Comment by pzuliani** [comment]
@soonhokong Does dReal 3 support ODEs yet? In case you want to try, you may have a look at the models here https://github.com/dreal/probreach/tree/master/model

The most difficult ones are prostate cancer (which you know already) and cars. BTW @danbryce, the cars scenario could be better modelled as a composition of two automata ...

**Comment by soonhokong** [comment]
> @soonhokong Does dReal 3 support ODEs yet? 

Yes.

> In case you want to try, you may have a look at the models here https://github.com/dreal/probreach/tree/master/model

They are pdrh files. Could you hand me some smt2 files that you get while solving the pdrh files? @shmarovfedor, could you help?

**Comment by pzuliani** [comment]
Nice - I will try ProbReach then :)

**Comment by shmarovfedor** [comment]
@soonhokong This is the kind of smt2 files we are generating for the prostate cancer model. This example is quite heavy and I do not know yet what the result should be.

```
(set-logic QF_NRA_ODE)
(declare-fun v () Real)
(declare-fun v_0_0 () Real)
(declare-fun v_0_t () Real)
(declare-fun x () Real)
(declare-fun x_0_0 () Real)
(declare-fun x_0_t () Real)
(declare-fun y () Real)
(declare-fun y_0_0 () Real)
(declare-fun y_0_t () Real)
(declare-fun z () Real)
(declare-fun z_0_0 () Real)
(declare-fun z_0_t () Real)
(declare-fun alphay () Real)
(declare-fun alphay_0_0 () Real)
(declare-fun alphay_0_t () Real)
(declare-fun betax () Real)
(declare-fun betax_0_0 () Real)
(declare-fun betax_0_t () Real)
(declare-fun t () Real)
(declare-fun t_0_0 () Real)
(declare-fun t_0_t () Real)
(declare-fun time_0 () Real)
(define-ode flow_1 ((= d/dt[alphay] 0.0)(= d/dt[betax] 0.0)(= d/dt[t] 1.0)(= d/dt[v] (+ (* (- (- (- (/ 0.0197 (+ 1.0 (exp (* (- 10.0 z) 1.0)))) (/ betax (+ 1.0 (exp (* (- z 10.0) 2.0))))) (* 5.0E-5 (- 1.0 (/ z 12.0)))) 0.01) x) (+ 0.02 (+ (* 5.0E-5 (* (- 1.0 (/ z 12.0)) x)) (* (- (* alphay (- 1.0 (* 1.0 (/ z 12.0)))) 0.0168) y)))))(= d/dt[x] (+ (* (- (- (- (/ 0.0197 (+ 1.0 (exp (* (- 10.0 z) 1.0)))) (/ betax (+ 1.0 (exp (* (- z 10.0) 2.0))))) (* 5.0E-5 (- 1.0 (/ z 12.0)))) 0.01) x) 0.02))(= d/dt[y] (+ (* 5.0E-5 (* (- 1.0 (/ z 12.0)) x)) (* (- (* alphay (- 1.0 (* 1.0 (/ z 12.0)))) 0.0168) y)))(= d/dt[z] (+ (* (- 0.0 z) 0.08) 0.03))))
(assert (>= v_0_0 0))
(assert (<= v_0_0 100))
(assert (>= v_0_t 0))
(assert (<= v_0_t 100))
(assert (>= x_0_0 0))
(assert (<= x_0_0 100))
(assert (>= x_0_t 0))
(assert (<= x_0_t 100))
(assert (>= y_0_0 0))
(assert (<= y_0_0 100))
(assert (>= y_0_t 0))
(assert (<= y_0_t 100))
(assert (>= z_0_0 0))
(assert (<= z_0_0 100))
(assert (>= z_0_t 0))
(assert (<= z_0_t 100))
(assert (>= alphay_0_0 0))
(assert (<= alphay_0_0 0.025))
(assert (>= alphay_0_t 0))
(assert (<= alphay_0_t 0.025))
(assert (>= betax_0_0 0))
(assert (<= betax_0_0 0.025))
(assert (>= betax_0_t 0))
(assert (<= betax_0_t 0.025))
(assert (>= time_0 0))
(assert (<= time_0 83))
(assert (>= t_0_0 0))
(assert (<= t_0_0 83))
(assert (>= t_0_t 0))
(assert (<= t_0_t 83))
(assert 
(and 
(= [v_0_t x_0_t y_0_t z_0_t alphay_0_t betax_0_t t_0_t] (integral 0. time_0 [v_0_0 x_0_0 y_0_0 z_0_0 alphay_0_0 betax_0_0 t_0_0] flow_1))
(= alphay_0_0 alphay_0_t)
(= betax_0_0 betax_0_t)
(= t_0_0 0)
(>= v_0_0 19.0998)
(<= v_0_0 19.1002)
(>= x_0_0 18.9998)
(<= x_0_0 19.0002)
(>= y_0_0 0.099999)
(<= y_0_0 0.100001)
(>= z_0_0 12.4999)
(<= z_0_0 12.5001)
(= t_0_t 83)
(>= v_0_t 1.1)
(<= v_0_t 3.9)
)
)
(check-sat)
(exit)
```

**Comment by soonhokong** [comment]
@shmarovfedor and @pzuliani 
![screen shot 2015-04-21 at 5 24 53 pm](https://cloud.githubusercontent.com/assets/403281/7262922/626f8962-e84b-11e4-9c55-1ecd576d6c48.png)

```bash
$ time ./dReal ../../src/tests/nra_ode/prostate_shmarov_01.smt2 --precision=0.005 --visualize  2>&1 | tee log
Solution:
alphay_0_0 : [0, 0.02500000000000001] = [0, 0.003125000000000001]
alphay_0_t : [0, 0.02500000000000001] = [0, 0.003125000000000001]
betax_0_0 : [0, 0.02500000000000001] = [0.02187500000000001, 0.02500000000000001]
betax_0_t : [0, 0.02500000000000001] = [0.02187500000000001, 0.02500000000000001]
t_0_0 : [0, 83] = [0, 0]
t_0_t : [0, 83] = [83, 83]
time_0 : [0, 83] = [82.99999999999999, 83]
v_0_0 : [0, 100] = [19.09980000000001, 19.10020000000001]
v_0_t : [0, 100] = [1.100000000000001, 1.102734375000001]
x_0_0 : [0, 100] = [18.99980000000001, 19.00020000000001]
x_0_t : [0, 100] = [1.76699465451402, 1.769830922017253]
y_0_0 : [0, 100] = [0.09999900000000001, 0.1000010000000001]
y_0_t : [0, 100] = [0.03305944995675374, 0.03491716237972323]
z_0_0 : [0, 100] = [12.49990000000001, 12.50010000000001]
z_0_t : [0, 100] = [0.3908475746287913, 0.3908478360342409]
delta-sat with delta = 0.00500000000000000
./dReal ../../src/tests/nra_ode/prostate_shmarov_01.smt2 --precision=0.005  2  11.33s user 0.02s system 99% cpu 11.453 total
```

**Comment by soonhokong** [comment]
@shmarovfedor and @pzuliani, can you confirm that the result is OK? It only takes 12sec on my machine.

One thing that we change in dReal3 is that the order of variables in an integral expression matters. Let me take an exmaple here. The SMT2 formula that @shmarovfedor wrote defined flow_1 as follows:

```
(define-ode flow_1 ((= d/dt[alphay] 0.0)
                    (= d/dt[betax] 0.0)
                    (= d/dt[t] 1)
                    (= d/dt[v] (+ (* (- (- (- (/ 0.0197 (+ 1 (exp (- 10.0 z) ))) (/ betax (+ 1 (exp (* (- z 10.0) 2.0))))) (* 0.00005 (- 1 (/ z 12.0)))) 0.01) x) (+ 0.02 (+ (* 0.00005 (* (- 1 (/ z 12.0)) x)) (* (- (* alphay (- 1 (/ z 12.0))) 0.0168) y)))))
                    (= d/dt[x] (+ (* (- (- (- (/ 0.0197 (+ 1 (exp (- 10.0 z) ))) (/ betax (+ 1 (exp (* (- z 10.0) 2.0))))) (* 0.00005 (- 1 (/ z 12.0)))) 0.01) x) 0.02))
                    (= d/dt[y] (+ (* 0.00005 (* (- 1 (/ z 12.0)) x)) (* (- (* alphay (- 1 (/ z 12.0))) 0.0168) y)))
                    (= d/dt[z] (+ (* (- 0.0 z) 0.08) 0.03))))
```

Here the variable ordering is `alphay`, `betax`, `t`, `v`, `x`, `y`, and `z`. In dReal3, we expect you use this ordering in an integral expression. The following is wrong in that sense:

```lisp
(= [v_0_t x_0_t y_0_t z_0_t alphay_0_t betax_0_t t_0_t] 
    (integral 0. time_0 [v_0_0 x_0_0 y_0_0 z_0_0 alphay_0_0 betax_0_0 t_0_0]
    flow_1))
```

The right one is
```lisp
(= [alphay_0_t betax_0_t t_0_t v_0_t x_0_t y_0_t z_0_t]
    (integral 0. time_0 [alphay_0_0 betax_0_0 t_0_0 v_0_0 x_0_0 y_0_0 z_0_0] flow_1))
```

I believe that @shmarovfedor got the above SMT2 file from dReach. Yes, there was a problem in dReach which messed up with the variable ordering. I fixed the problem in dReal3. So, if you use dReach in dReal3, you shouldn't experience this problem (or if you have, please let me know).

**Comment by soonhokong** [comment]
It would be great if I can have more benchmarks. My main concern is that we might have an example which works really nice with dReal2, but not with dReal3. If there is any, I want to work on it before making the first official release of dReal3.

**Comment by shmarovfedor** [comment]
Wow. That is very impressive. It is much faster than dReal2 (which is still running). I guess I should start using it now. Also I will get some more benchmarks later.

Did not know that ODE order matters. @soonhokong Thanks for clarification

**Comment by soonhokong** [comment]
@shmarovfedor, great! Just let me know if you need anything for the migration.

**Comment by scungao** [comment]
Looking fantastic!

**Comment by shmarovfedor** [comment]
@soonhokong This is kind of funny but the model above with wrong ODE ordering works much faster in dReal3 than the one with correct ordering.

**Comment by soonhokong** [comment]
@shmarovfedor: Yes, that is the case. What happen is that dReal3 is solving the problem with a different initial condition (which is wrong). Then, the ode integration quickly diverges and keeps failing with an exception. It means that the ODE pruning is not working at all and the solving process merely relies on branching. After a series of branching, it terminates just because the current box is small enough.

@scungao, I think we need to distinguish the two cases in delta-sat -- one we can get a trace, one we fails to get a trace. Do you have any good suggestion?

**Comment by soonhokong** [comment]
@shmarovfedor, just as a reminder, the current dReal3 doesn't use mode invariants in pruning. As a result, it could give you a wrong result (returns delta-SAT while it should be UNSAT due to a violation of mode invariant). Also, it could be way slower because mode invariant gives some extra pruning power in general. I do have both of cases in the benchmarks and working on adding support for mode invariants.

**Comment by shmarovfedor** [comment]
Oh. I see. Thanks @soonhokong

**Comment by scungao** [comment]
When it diverges, the ODE solver does not provide a "well-defined" pruning operator, which makes the procedure not delta-complete. I think we should return "ODE pruning fails" in those cases instead of delta-sat.

**Comment by danbryce** [comment]
I think I'm ready to merge the changes for networks of automata and associated heuristics.  Is there a git way to do it smoothly, or should I use cut/paste?

**Comment by soonhokong** [comment]
@danbryce, I would try either [git-rebase](https://www.atlassian.com/git/tutorials/rewriting-history) or [git-cherry-pick](http://think-like-a-git.net/sections/rebase-from-the-ground-up/cherry-picking-explained.html).

**Comment by danbryce** [comment]
I didn’t realize there was a shared history.  I’ll give it a shot.

**Comment by soonhokong** [comment]
Let me close this one. See [First Official Release](https://github.com/dreal/dreal3/milestones/First%20official%20release) to check the current items and their progresses.

**Comment by scungao** [comment]
Github should introduce a "like" button.

**Comment by soonhokong** [comment]
People do :+1:(`:+1: `).

**Comment by scungao** [comment]
on the "milestone"

**Comment by soonhokong** [comment]
haha...
